sudo: required
services: 
  - docker
language: 
  - java #backend
  - node_js #frontend
node_js:
  - "7"
jdk:
  - oraclejdk8
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &
before_script: 
  - cd  Frontend/data-breach-visualization/src
  - npm install -g @angular/cli
  - npm install 
  - ng build
  - echo 'Front end build successful'
script:
  - ng test
after_success: 
  - cd ../../Backend/security-breach-data
  - docker build -t sec-viz-back .
  - cd  ../../Frontend/data-breach-visualization
  - docker build -t sec-viz-front .
  - echo 'Docker images built successfully'