sudo: required
services: 
  - docker
language: java
jdk:
  - oraclejdk8
before_script: cd Backend/security-breach-data
after_success: 
  - docker --v
  - docker build -t backend .
  - echo 'Build Successful'