sudo: required
services: 
  - docker
language: 
  - java #backend
  - node_js #frontend
node_js:
  - "7"
jdk:
  - oraclejdk8
before_script: 
  - cd Backend/security-breach-data
  - npm install -g @angular/cli
script:
  - ng build -aot --prod
  - echo 'Front end build successful'
after_success: 
  - docker build -t sec-viz .
  - echo 'Docker image build successful'