sudo: required
services: 
  - docker
language: 
  - java #backend
  - node_js #frontend
node_js:
  - "7"
jdk:
  - oraclejdk8
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: 
  - cd  Frontend/data-breach-visualization/src
  - npm install -g @angular/cli
  - npm install 
  - ng build
  - echo 'Front end build successful'
script:
  - ./node_modules/.bin/karma start --browsers Firefox --single-run   
after_success: 
  - cd ../../Backend/security-breach-data
  - docker build -t sec-viz-back .
  - cd  ../../Frontend/data-breach-visualization
  - docker build -t sec-viz-front .
  - echo 'Docker images built successfully'