sudo: required
services: 
  - docker
language: 
  - java #backend
  - node_js #frontend
node_js:
  - "7"
jdk:
  - oraclejdk8
before_script: 
  - cd  Frontend/data-breach-visualization/src/app
  - npm install -g @angular/cli
  - npm install 
  - ng build --prod
  - echo 'Front end build successful'
after_success: 
  - cd ../../Backend/security-breach-data
  - docker build -t sec-viz-back .
  - cd  ../../Frontend/data-breach-visualization
  - docker build -t sec-viz-front .
  - echo 'Docker images built successfully'